name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for #skip in commit messages or PR title
        id: check_skip
        run: |
          SKIP="false"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            TITLE="${{ github.event.pull_request.title }}"
            if echo "$TITLE" | grep -q "#skip"; then
              SKIP="true"
            fi
          else
            COMMITS=$(git log -1 --pretty=%B)
            if echo "$COMMITS" | grep -q "#skip"; then
              SKIP="true"
            fi
          fi
          echo "::set-output name=skip::$SKIP"

  simple_deployment_pipeline:
    needs: check_skip

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npm run eslint

      - name: Run tests
        run: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npx playwright test

      - name: Run build
        run: npm run build

      - name: Deploy
        # Only run this step if the branch is main and skip is false
        if: github.ref == 'refs/heads/main' && needs.check_skip.outputs.skip != 'true'

        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

  # tag_release:
  #   needs: [simple_deployment_pipeline]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Bump version and push tag
  #       if: github.ref == 'refs/heads/main'
  #       uses: anothrNick/github-tag-action@1.75.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DEFAULT_BUMP: patch
  #
  # Decided to use npm version to bump and tag instead of the action above
  # because it updates package.json and package-lock.json as well.

  tag_release:
    needs: [simple_deployment_pipeline, check_skip]
    if: github.ref == 'refs/heads/main' && needs.check_skip.outputs.skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump version and tag
        run: |
          npm version patch -m "Bump version to %s"
          git push --follow-tags
