name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npm run eslint

      - name: Run tests
        run: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npx playwright test

      - name: Run build
        run: npm run build

      - name: Deploy
        # Only run this step if the branch is main and skip is false
        if: |
          github.ref == 'refs/heads/main' &&
          !contains(github.event.head_commit.message || github.event.pull_request.title, '#skip')

        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

      - uses: yu-iskw/merged-pr-info-action@v1.0.1
        id: merged-pr-info
        if: github.ref == 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Discord notification sucess
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        if: success() &&
          github.ref == 'refs/heads/main' &&
          !contains(github.event.head_commit.message || github.event.pull_request.title, '#skip')
        with:
          args: >
            âŒ Deployment Succeeded for PR #${{ steps.merged-pr-info.outputs.pull-request-number }}: {{ EVENT_PAYLOAD.pull_request.title }

      - name: Discord notification failure
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        if: failure() &&
          github.ref == 'refs/heads/main' &&
          !contains(github.event.head_commit.message || github.event.pull_request.title, '#skip')
        with:
          args: >
            ðŸ¤© Deployment succeed for PR #${{ steps.merged-pr-info.outputs.pull-request-number }}: {{ EVENT_PAYLOAD.pull_request.title }

  tag_release:
    needs: [simple_deployment_pipeline]
    if: |
      github.ref == 'refs/heads/main' &&
      !contains(github.event.head_commit.message || github.event.pull_request.title, '#skip')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: github.ref == 'refs/heads/main'
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
