name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npm run eslint

      - name: Run tests
        run: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npx playwright test

      - name: Run build
        run: npm run build

      - name: Deploy
        # Only run this step if the branch is main and skip is false
        if: |
          github.ref == 'refs/heads/main' &&
          !contains(github.event.head_commit.message || github.event.pull_request.title, '#skip')

        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

  # tag_release:
  #   needs: [simple_deployment_pipeline]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Bump version and push tag
  #       if: github.ref == 'refs/heads/main'
  #       uses: anothrNick/github-tag-action@1.75.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DEFAULT_BUMP: patch
  #
  # Decided to use npm version to bump and tag instead of the action above
  # because it updates package.json and package-lock.json as well.

  tag_release:
    needs: [simple_deployment_pipeline]
    if: |
      github.ref == 'refs/heads/main' &&
      !contains(github.event.head_commit.message || github.event.pull_request.title, '#skip')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump version and save
        id: bump
        run: |
          NEW_VERSION=$(npm version patch --no-git-tag-version)
          git commit -am "Bump version to $NEW_VERSION"
          git push
          echo "BUMPED_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Tag the release
        run: |
          git tag "$BUMPED_VERSION"
          git push origin --tags

      - name: Notify Discord on success
        uses: Ilshidur/action-discord@master
        if: success()
        with:
          args: >
            webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
            message: "✅ Deployment pipeline succeeded for ${{ env.BUMPED_VERSION }}"
            severity: "info"

      - name: Notify Discord on failure
        uses: Ilshidur/action-discord@master
        if: failure()
        with:
          args: >
            webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
            severity: "error"
            message: |
              ❌ Deployment pipeline failed. |
                 Commit: ${{ github.sha }}
